linked sponor button
acm-ucr/vex-robotics-website pull request #164
Opened 2024-05-31 15:02 UTC by GitHaresco

linked the sponsor button to ucrvexrobotics@gmail.com, but it goes to a 404 error page

![image](https://github.com/acm-ucr/vex-robotics-website/assets/162786819/5b7cc622-d099-4199-b96f-2fe41f81ddd7)
![image](https://github.com/acm-ucr/vex-robotics-website/assets/162786819/8072bfbf-d1cf-4d23-9c47-63ca4c596124)

2024-06-05 08:15 UTC, SafeDuck requested changes

2024-06-05 08:15 UTC, SafeDuck commented on src/components/home/Sponsors.jsx
> +            link="ucrvexrobotics@gmail.com"
check out the other buttons to see how they linked to an email

2024-06-07 17:32 UTC, GitHaresco commented
linked to "mailto: ucrvexrobotics@gmail.com"

2024-06-11 03:50 UTC, SafeDuck approved these changes

2024-06-11 03:50 UTC, merged