Created button component
acm-ucr/vex-robotics-website pull request #30
Opened 2024-04-09 21:02 UTC by sunbrandon

2024-04-10 06:08 UTC, SafeDuck requested changes

2024-04-10 06:08 UTC, SafeDuck commented on src/components/Button.jsx
> +      <button style={{ backgroundColor: color }}>{text}</button>
when you use `style` tag it is just regular CSS
but we are using tailwindCSS for this project, so use `className=""` instead
specifically you want to do `className={`${color}`}`

Also it looks like you didn't finish styling the button, like you didn't round the corners, you didn't put a width on it either, you will also need some padding

2024-04-11 06:33 UTC, sunbrandon commented
<img width="166" alt="Screenshot 2024-04-10 at 11 30 27 PM" src="https://github.com/acm-ucr/vex-robotics-website/assets/132787942/7bf9b708-a3a3-4b2c-be37-f9a0f3d02ea2">

2024-04-12 18:22 UTC, SafeDuck approved these changes

2024-04-12 18:22 UTC, merged