Created Title.jsx in components
acm-ucr/vex-robotics-website pull request #32
Opened 2024-04-10 20:19 UTC by GitHaresco

Just created the file in components. Let me know what I'm missing/a better way to do this.

2024-04-11 04:13 UTC, GitHaresco commented
![image_2024-04-10_211349777](https://github.com/acm-ucr/vex-robotics-website/assets/162786819/56a08f6b-345f-45c0-9dc6-df1a94de609a)

2024-04-12 00:20 UTC, SafeDuck requested changes

2024-04-12 00:20 UTC, SafeDuck commented on src/components/Title.jsx
> +    <div class="font-russo" style={{ fontSize: "110px", color: "#FFFFFF" }}>
you want to use tailwind classes, instead of regular css
checkout the documentation:
https://tailwindcss.com/docs/text-color

2024-04-17 21:55 UTC, SafeDuck requested changes

2024-04-17 21:55 UTC, SafeDuck commented on src/components/Title.jsx
> +  return <div class="font-russo text-white text-[110px]">ABOUT US</div>;
change `text-[110px]`
It's a better idea to use the built in tailwind classes
https://tailwindcss.com/docs/font-size

2024-04-17 22:05 UTC, GitHaresco commented
![image](https://github.com/acm-ucr/vex-robotics-website/assets/162786819/3081ffd4-ba8a-4474-b95b-0767f3abc61f)

2024-04-17 22:16 UTC, SafeDuck approved these changes

2024-04-17 22:16 UTC, merged